<a href="https://www.kaggle.com/code/shravankumar147/multi-table-extraction-from-pdf?scriptVersionId=219099424" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Table Extraction from PDF

## Step 1: Install Required Libraries

In [1]:
!pip install reportlab pandas lorem pymupdf -q -U

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 2.0 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 25.9 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 67.3 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.0/20.0 MB 66.2 MB/s eta 0:00:00:00:0100:01
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires notebook==6.5.5, but you have notebook 6.5.4 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.
mlxtend 0.23.3 requires scikit-learn>=1.3.1, but you have scikit-learn 1.2.2 which is incompatible.
pandas-gbq 0.25.0 requires google-api-core<3.0.0dev,>=2.10.2, but you have google-api-core 1.34.1 which is incompatible.
plotnine 0.14.4 requires matplotlib>=3.8.0, but you have matplotlib 3.7.5 which is incompatible.
tensorflow-decision-forests 1.10.0 requires tensorflow==2.17.0, but you have tensorflow 2.17.1 which is incompatible.

## Step 2: Create the PDF with Multiple Pages, Tables, and Random Text

In [2]:
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
import pandas as pd
import lorem  # For generating random text

# Sample data for tables
data1 = {
    'ID': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'Occupation': ['Engineer', 'Doctor', 'Artist', 'Lawyer', 'Teacher']
}

data2 = {
    'Product': ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry'],
    'Price': [1.20, 0.50, 2.50, 1.80, 3.00],
    'Stock': [100, 200, 150, 300, 75]
}

data3 = {
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Population (M)': [8.5, 4.0, 2.7, 2.3, 1.7],
    'Area (sq mi)': [302.6, 468.7, 227.3, 637.5, 517.6]
}

data4 = {
    'Animal': ['Lion', 'Tiger', 'Elephant', 'Giraffe', 'Zebra'],
    'Lifespan (years)': [10, 15, 60, 25, 25],
    'Habitat': ['Savanna', 'Forest', 'Savanna', 'Savanna', 'Savanna']
}

# Create DataFrames
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)
df4 = pd.DataFrame(data4)

# Function to create a table with style
def create_table(dataframe):
    table_data = [dataframe.columns.to_list()] + dataframe.values.tolist()
    table = Table(table_data)
    style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ])
    table.setStyle(style)
    return table

# Create a PDF document
pdf_filename = "multi_page_tables_with_text.pdf"
doc = SimpleDocTemplate(pdf_filename, pagesize=letter)

# Create a list to hold the elements of the PDF
elements = []

# Add a title to the PDF
styles = getSampleStyleSheet()
title = Paragraph("Multi-Page PDF with Tables and Random Text", styles['Title'])
elements.append(title)
elements.append(Spacer(1, 12))  # Add some space

# Page 1: Add text and table 1
elements.append(Paragraph("This is the first page of the PDF.", styles['BodyText']))
elements.append(Spacer(1, 12))
elements.append(Paragraph(lorem.paragraph(), styles['BodyText']))  # Random text
elements.append(Spacer(1, 12))
elements.append(Paragraph("Below is a table with employee data:", styles['BodyText']))
elements.append(Spacer(1, 12))
elements.append(create_table(df1))
elements.append(Spacer(1, 12))
elements.append(Paragraph(lorem.paragraph(), styles['BodyText']))  # Random text

# Page 2: Add text and table 2
elements.append(Paragraph("This is the second page of the PDF.", styles['BodyText']))
elements.append(Spacer(1, 12))
elements.append(Paragraph(lorem.paragraph(), styles['BodyText']))  # Random text
elements.append(Spacer(1, 12))
elements.append(Paragraph("Below is a table with product data:", styles['BodyText']))
elements.append(Spacer(1, 12))
elements.append(create_table(df2))
elements.append(Spacer(1, 12))
elements.append(Paragraph(lorem.paragraph(), styles['BodyText']))  # Random text

# Page 3: Add text and table 3
elements.append(Paragraph("This is the third page of the PDF.", styles['BodyText']))
elements.append(Spacer(1, 12))
elements.append(Paragraph(lorem.paragraph(), styles['BodyText']))  # Random text
elements.append(Spacer(1, 12))
elements.append(Paragraph("Below is a table with city data:", styles['BodyText']))
elements.append(Spacer(1, 12))
elements.append(create_table(df3))
elements.append(Spacer(1, 12))
elements.append(Paragraph(lorem.paragraph(), styles['BodyText']))  # Random text

# Page 4: Add text and table 4
elements.append(Paragraph("This is the fourth page of the PDF.", styles['BodyText']))
elements.append(Spacer(1, 12))
elements.append(Paragraph(lorem.paragraph(), styles['BodyText']))  # Random text
elements.append(Spacer(1, 12))
elements.append(Paragraph("Below is a table with animal data:", styles['BodyText']))
elements.append(Spacer(1, 12))
elements.append(create_table(df4))
elements.append(Spacer(1, 12))
elements.append(Paragraph(lorem.paragraph(), styles['BodyText']))  # Random text

# Build the PDF
doc.build(elements)

print(f"PDF created successfully: {pdf_filename}")

PDF created successfully: multi_page_tables_with_text.pdf

## Helper function to extract tables

In [3]:
import fitz  # PyMuPDF
import pandas as pd

def extract_tables_with_context(pdf_path, context_window=300):
    """Extract tables with surrounding context from PDF using find_tables()"""
    doc = fitz.open(pdf_path)
    table_data = []
    
    for page_num in range(len(doc)):
        page = doc.load_page(page_num)
        
        # Find tables on the page
        tables = page.find_tables()
        
        if tables.tables:  # Check if any tables were found
            for table_num, table in enumerate(tables.tables):
                try:
                    # Extract table as DataFrame
                    df = table.to_pandas()
                    
                    # Get bounding box of the table
                    table_bbox = table.bbox
                    
                    # If table_bbox is a tuple, convert it to a fitz.Rect object
                    if isinstance(table_bbox, tuple):
                        table_bbox = fitz.Rect(table_bbox)
                    
                    # Get surrounding context
                    y0 = max(0, table_bbox.y0 - context_window)
                    context = page.get_text("text", clip=(0, y0, page.rect.width, table_bbox.y0))
                    
                    table_data.append({
                        "page": page_num + 1,
                        "table_num": table_num + 1,
                        "context": context.strip(),
                        "table": df.to_markdown(index=False),
                        "full_text": f"Context: {context}\nTable:\n{df.to_markdown(index=False)}"
                    })
                except Exception as e:
                    print(f"Error on page {page_num} table {table_num}: {str(e)[:50]}")
        else:
            print(f"No tables found on page {page_num + 1}")
    
    return table_data

## Test over the PDF

In [8]:
pdf_path = "multi_page_tables_with_text.pdf"  # Replace with your PDF path
tables_with_context = extract_tables_with_context(pdf_path)

# Print the extracted data
for table in tables_with_context:
    print(f"Page: {table['page']}, Table: {table['table_num']}")
    print(table['table'])
    print("-" * 50)

No tables found on page 3
Page: 1, Table: 1
|   ID | Name    |   Age | Occupation   |
|-----:|:--------|------:|:-------------|
|    1 | Alice   |    24 | Engineer     |
|    2 | Bob     |    27 | Doctor       |
|    3 | Charlie |    22 | Artist       |
|    4 | David   |    32 | Lawyer       |
|    5 | Eva     |    29 | Teacher      |
--------------------------------------------------
Page: 1, Table: 2
| Product    |   Price |   Stock |
|:-----------|--------:|--------:|
| Apple      |     1.2 |     100 |
| Banana     |     0.5 |     200 |
| Cherry     |     2.5 |     150 |
| Date       |     1.8 |     300 |
| Elderberry |     3   |      75 |
--------------------------------------------------
Page: 2, Table: 1
| City        |   Population (M) |   Area (sq mi) |
|:------------|-----------------:|---------------:|
| New York    |              8.5 |          302.6 |
| Los Angeles |              4   |          468.7 |
| Chicago     |              2.7 |          227.3 |
| Houston     |              2.3 |          637.5 |
| Phoenix     |              1.7 |          517.6 |
--------------------------------------------------
Page: 2, Table: 2
| Animal   |   Lifespan (years) | Habitat   |
|:---------|-------------------:|:----------|
| Lion     |                 10 | Savanna   |
| Tiger    |                 15 | Forest    |
| Elephant |                 60 | Savanna   |
| Giraffe  |                 25 | Savanna   |
| Zebra    |                 25 | Savanna   |
--------------------------------------------------